question_data = [
     {"category":"General Knowledge","type":"boolean","difficulty":"easy","question":"Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.","correct_answer":"False","incorrect_answers":["True"]},
                {"category":"General Knowledge","type":"boolean","difficulty":"easy","question":"Nutella is produced by the German company Ferrero.","correct_answer":"False","incorrect_answers":["True"]},
                {"category":"General Knowledge","type":"boolean","difficulty":"easy","question":"&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.","correct_answer":"True","incorrect_answers":["False"]},
                {"category":"General Knowledge","type":"boolean","difficulty":"easy","question":"In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.","correct_answer":"True","incorrect_answers":["False"]},
                {"category":"General Knowledge","type":"boolean","difficulty":"easy","question":"Adolf Hitler was born in Australia. ","correct_answer":"False","incorrect_answers":["True"]},
                {"category":"General Knowledge","type":"boolean","difficulty":"easy","question":"One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.","correct_answer":"True","incorrect_answers":["False"]},
                {"category":"General Knowledge","type":"boolean","difficulty":"easy","question":"&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.","correct_answer":"True","incorrect_answers":["False"]},
                {"category":"General Knowledge","type":"boolean","difficulty":"easy","question":"Scotland voted to become an independent country during the referendum from September 2014.","correct_answer":"False","incorrect_answers":["True"]},
                {"category":"General Knowledge","type":"boolean","difficulty":"easy","question":"Vietnam&#039;s national flag is a red star in front of a yellow background.","correct_answer":"False","incorrect_answers":["True"]},
                {"category":"General Knowledge","type":"boolean","difficulty":"easy","question":"Slovakia is a member of European Union-","correct_answer":"True","incorrect_answers":["False"]}
]